from __future__ import annotations

from typing import Protocol
from uuid import UUID

from loanlens.models import (
    LoanProfile,
    Moratorium,
    ODAccount,
    ODTransaction,
    Payment,
    RateRevision,
    ScheduleRow,
    SimulationResult,
)


class StoreBase(Protocol):
    def get_loan(self, loan_id: UUID) -> LoanProfile | None: ...
    def save_loan(self, loan: LoanProfile) -> None: ...
    def list_loans(self) -> list[LoanProfile]: ...
    def get_schedule(self, loan_id: UUID) -> list[ScheduleRow]: ...
    def save_schedule(self, loan_id: UUID, rows: list[ScheduleRow]) -> None: ...
    def get_od_account(self, loan_id: UUID) -> ODAccount | None: ...
    def save_od_account(self, account: ODAccount) -> None: ...
    def list_od_transactions(self, od_account_id: UUID) -> list[ODTransaction]: ...
    def add_od_transaction(self, txn: ODTransaction) -> None: ...
    def list_payments(self, loan_id: UUID) -> list[Payment]: ...
    def add_payment(self, payment: Payment) -> None: ...
    def list_rate_revisions(self, loan_id: UUID) -> list[RateRevision]: ...
    def add_rate_revision(self, revision: RateRevision) -> None: ...
    def list_moratoriums(self, loan_id: UUID) -> list[Moratorium]: ...
    def add_moratorium(self, moratorium: Moratorium) -> None: ...
    def save_simulation(self, result: SimulationResult) -> None: ...
    def get_simulation(self, simulation_id: UUID) -> SimulationResult | None: ...
    def list_simulations(self, loan_id: UUID) -> list[SimulationResult]: ...
    def append_audit(self, entry: dict[str, object]) -> None: ...
