"""
test_parity.py — TS↔Python parity test suite.

Verifies that the Python engine produces **identical** output to the
TypeScript engine for all 8 golden fixture scenarios generated by
`scripts/generate-fixtures.ts`.

Tolerance rules (per P1-07 spec):
  - Integer money fields: exact match (±0)
  - Date strings: exact match
  - Period number: exact match
  - Phase string: exact match
  - Percentage fields (effectiveInterestRate): match to 2 decimal places
  - Schedule length: exact match
"""

from __future__ import annotations

import glob
import json
import os
from pathlib import Path

import pytest

from engine.metrics import calculate_metrics
from engine.schedule import generate_schedule
from engine.types import LoanData

# ---------------------------------------------------------------------------
# Fixture discovery
# ---------------------------------------------------------------------------

_FIXTURES_DIR = Path(__file__).resolve().parent.parent / "fixtures"
_FIXTURE_PATHS = sorted(glob.glob(str(_FIXTURES_DIR / "*.json")))

# Sanity-check: we expect exactly 8 fixtures
assert len(_FIXTURE_PATHS) == 8, (
    f"Expected 8 fixture files in {_FIXTURES_DIR}, found {len(_FIXTURE_PATHS)}"
)

# The pinned date used when generating fixtures via generate-fixtures.ts
_PINNED_TODAY = "2026-09-19"

# Fields compared per schedule row (all must match exactly)
_SCHEDULE_FIELDS = [
    "period",
    "dueDate",
    "openingBalance",
    "installment",
    "interest",
    "baselineInterest",
    "interestSavings",
    "principal",
    "closingBalance",
    "phase",
    "effectivePrincipal",
]

# Metrics fields that must match exactly (integers, strings, dates)
_METRICS_EXACT_FIELDS = [
    "currentPhase",
    "outstandingPrincipal",
    "effectivePrincipal",
    "nextDueDate",
    "nextInstallmentAmount",
    "projectedEmi",
    "projectedClosureDate",
    "interestPaidToDate",
    "principalPaidToDate",
    "totalInterestProjected",
    "interestSavedTillNow",
    "interestSavedThisYear",
    "disbursedAmount",
    "sanctionedAmount",
]

# Metrics fields compared with 2-decimal-place tolerance
_METRICS_APPROX_FIELDS = [
    "effectiveInterestRate",
]


def _fixture_id(path: str) -> str:
    """Extract scenario name from fixture path for readable test IDs."""
    return Path(path).stem


def _load_fixture(path: str) -> dict:
    with open(path) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Schedule parity tests
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("fixture_path", _FIXTURE_PATHS, ids=_fixture_id)
def test_schedule_parity(fixture_path: str) -> None:
    """Verify Python schedule matches TS-generated expected_schedule row by row."""
    fixture = _load_fixture(fixture_path)
    scenario = fixture["scenario"]

    data = LoanData(**fixture["input"])
    schedule = generate_schedule(data, _PINNED_TODAY)
    expected = fixture["expected_schedule"]

    # Check schedule length first for a clear error message
    assert len(schedule) == len(expected), (
        f"[{scenario}] Schedule length mismatch: "
        f"Python={len(schedule)}, TS={len(expected)}"
    )

    # Row-by-row, field-by-field comparison
    for i, (actual_row, expected_row) in enumerate(zip(schedule, expected)):
        for field in _SCHEDULE_FIELDS:
            actual_val = getattr(actual_row, field)
            expected_val = expected_row[field]
            assert actual_val == expected_val, (
                f"[{scenario}] Row {i} (period {expected_row['period']}), "
                f"field '{field}': Python={actual_val!r}, TS={expected_val!r}"
            )


# ---------------------------------------------------------------------------
# Metrics parity tests
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("fixture_path", _FIXTURE_PATHS, ids=_fixture_id)
def test_metrics_parity(fixture_path: str) -> None:
    """Verify Python metrics match TS-generated expected_metrics for each scenario."""
    fixture = _load_fixture(fixture_path)
    scenario = fixture["scenario"]

    data = LoanData(**fixture["input"])
    schedule = generate_schedule(data, _PINNED_TODAY)
    metrics = calculate_metrics(data, schedule, _PINNED_TODAY)
    expected = fixture["expected_metrics"]

    # Exact-match fields
    for field in _METRICS_EXACT_FIELDS:
        if field not in expected:
            continue
        actual_val = getattr(metrics, field)
        expected_val = expected[field]
        assert actual_val == expected_val, (
            f"[{scenario}] Metrics field '{field}': "
            f"Python={actual_val!r}, TS={expected_val!r}"
        )

    # Approximate-match fields (2 decimal places)
    for field in _METRICS_APPROX_FIELDS:
        if field not in expected:
            continue
        actual_val = getattr(metrics, field)
        expected_val = expected[field]
        assert round(actual_val, 2) == round(expected_val, 2), (
            f"[{scenario}] Metrics field '{field}' (2dp): "
            f"Python={actual_val!r}, TS={expected_val!r}"
        )
